### ISSUE TITLE
Useful information on nurbs for you.

### ISSUE THREAD

**Issue by Zxynine** [komietty/unity-nurbs#6]
I have been programming for over 7 years now,  I also tutor most fields in stem, but never before has a coding/maths project gotten me so close to crying as trying to understand and implement nurbs vs bezier vs catmulllrom vs bspline and so on. i have spent days combing through papers and code projects in at least 4 different coding languages trying to wrap my head around it all, I do hope im not alone. I like what you have done so far with this, the spline is pretty and your code was nice to read. To return the favour i will provide you some of the best resources I have found to aid you in the design of this project and possibly even expand upon it if you so desire.

First off, a venn diagram of some various curves:
![image](https://user-images.githubusercontent.com/79198508/163662616-0554fadc-fd1c-42de-8d2e-0503227b5384.png)
That helped me a fair bit, you are already working on NURBS so that may not be as much of a concern for you, but if you wish to expand onto the other types, there you go.

Secondly, i have only found one resource that explained NURBS in a very simple, clean, elegant, step by step way which can be found here :
https://www.codeproject.com/Articles/1095142/Generate-and-understand-NURBS-curves
It includes some code in C# and for unity at that! I know you have a fair bit of that already implemented, but if you didn't understand it all fully then it may help.

Next, the primary reason I created this, I noticed in your code you said this:

```
		// IN PROGRESS:
		// To calcurate derivatives for openuniform knot vector, hodograph seems to be needed.
		// https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-derv.html
```
I have found a paper in which they have a graph showing the calculated derivative of a uniform knot vector curve which you may find helpful
![image](https://user-images.githubusercontent.com/79198508/163663103-4e085e0f-9651-454c-bb0d-be628d29498d.png)
It has a full couple of pages dedicated to spline and curves and can be found here: 
https://sci-hub.se/10.1016/j.cma.2014.11.011
The sc i showed you is found on page 8.

In the resource i linked in my second point, it also mentions:
```It is also possible to create a B-Spline function for any derivative of the B-Spline. I will not give the code here though, but it can be found in The NURBS book, where the code for Nip is from too.```
The book that it is referring to can be found here : https://argos.vu/wp-content/uploads/2019/03/Springer-TheNURBSBook.pdf
And has a ton of great info in it, but its a poor quality pdf and the code is in c++ which isnt as descriptive as something like C# is. I actually already started converting it into c# and commenting it, so it should save you some time, the only thing that needs to be finished with it is setting the proper size for the arrays before you add elements into them, even if you see a value there to define the size, you should check it since most of it i was putting in as I went converting it, I didnt actually think it through all that well.

```
			//create a B-Spline function for any derivative of the B-Spline.
			//Computes derivatives of basis function.

			/// <param name="i">Current control pont</param>
			/// <param name="p">The picewise polynomial degree</param>
			/// <param name="U">The knot vector</param>
			/// <param name="u">The value of the current curve point from 0 to 1 </param>
			/// <param name="n">The number of degrees?? </param>
			private double[] BasisDerivative(int i, int p, double[] U, double u,     int n) {
				int m = U.Length - 1;
				double[] ders = new double[n+1];
				if (u < U[i] || u >= U[i+p+1]) return ders;


				double[][] N = new double[p+1][];
				for (int j=0; j<=p; ++j) N[j] = new double[n+1];
				
				for (int j = 0; j<=p; ++j) { //Initialise zeroth degree funcs
					N[j][0] = (u >= U[i+j] && u < U[i+j+1])? 1d : 0d;
				}

				double saved, temp;
				//Compute Triangular table
				for (int k=1; k <= p; ++k) {
					saved = (N[0][k-1] != 0)?  ((u - U[i]) * N[0][k-1]) / (U[i+k] - U[i]) : 0;
					for (int j=0; j< p-k+1; ++j) {
						double Uleft = U[i+j +1];
						double Uright = U[i+j+k +1];

						if (N[j+1][k-1] == 0) {
							(N[j][k], saved) = (saved, 0d);
						} else {
							temp = N[j+1][k-1] / (Uright - Uleft);
							(N[j][k], saved) = (saved+(Uright-u)*temp, (u-Uleft)*temp);
						}
					}
				}

				ders[0] = N[0][p]; //The function value
				//Compute derivatives
				
				double[] ND = new double[n];
				for (int k=1; k < p; ++k) {
					for (int j=0; j <= k; ++j) ND[j] = N[j][p-k]; //Load appropriate column
					for (int h=1; h <= k; ++h) { //Compute table of width k
						saved = (ND[0] == 0)? 0d : ((ND[0]) / (U[i+k] - U[i]));

						for (int j = 0; j < k-h+1; ++j) {
							double Uleft = U[i+j+1];
							double Uright = U[i+j+p+h+1];

							if (ND[j+1] == 0) {
								(ND[j], saved) = (saved*(p-k+h), 0d);
							} else {
								temp = ND[j+1] / (Uright-Uleft);

								ND[j] = (p-k+h) * (saved-temp);
								saved = temp;
							}
						}

					}
					ders[k] = ND[0]; //Kth derivative
				}
				return ders;
			}
```

Lastly, 
I found a really nice github project around cubic bezier curves that has a nice editor and very indepth code. You should check it out and look through the code for ideas here : https://github.com/vvrvvd/Unity-Spline-Editor
Its the only one besides yours I directly downloaded to play with.

Lastly lastly: 
Heres some resources
/*
https://github.com/yolanother/UnitySplines
https://github.com/gregoiredelzongle/GPGre-Bezier-Splines
https://github.com/Kink3d/kSplines/blob/master/com.kink3d.splines/Runtime/Enum/Direction.cs
https://github.com/methusalah/SplineMesh/blob/master/Assets/SplineMesh/Scripts/Bezier/CubicBezierCurve.cs
https://github.com/dbrizov/NaughtyBezierCurves
https://github.com/Habrador/Computational-geometry
https://github.com/methusalah/SplineMesh
http://15462.courses.cs.cmu.edu/fall2015content/misc/CatmullRomReparameterization.pdf
https://github.com/JPBotelho/Catmull-Rom-Splines/blob/master/CatmullRom.cs
https://faramira.com/implement-bezier-curve-using-csharp-in-unity/
https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/Bezier/bezier-der.html
https://en.wikipedia.org/wiki/Centripetal_Catmull–Rom_spline
https://en.wikibooks.org/wiki/Cg_Programming/Unity/Hermite_Curves
https://en.wikipedia.org/wiki/Composite_Bézier_curve
https://github.com/stefnotch/flax-bspline-experiment/blob/master/Source/BSpline.cs
http://15462.courses.cs.cmu.edu/fall2020/article/10
https://stackoverflow.com/questions/4089443/find-the-tangent-of-a-point-on-a-cubic-bezier-curve
https://github.com/stefnotch/flax-bspline-experiment/blob/master/Source/BSpline.cs
https://github.com/Aclardgm/Unity_BSplinesTensorialProduct/blob/main/Assets/BSpline.cs
https://github.com/RomanBushuev/BsplineLangrangeInterpolate/blob/master/HomeWorkBushuev/HomeWorkBushuev/CubeSplain.cs

https://www.desmos.com/calculator/wmaois894o
https://www.desmos.com/calculator/3zzznsp78n

Compute a length of a spline segment by using 5-point Legendre-Gauss quadrature
https://github.com/Kink3d/kSplines/blob/master/com.kink3d.splines/Runtime/Util/SplineUtil.cs
https://medium.com/@all2one/how-to-compute-the-length-of-a-spline-e44f5f04c40
https://pomax.github.io/bezierinfo/legendre-gauss.html
https://en.wikipedia.org/wiki/Gaussian_quadrature
*/

**Comment by komietty** [comment]
Wow very informative! thank you!
